queue_rules:
  - name: default
    conditions:
      - check-success=ci-smoketests
      - check-success=ci-typing
      - check-success=ci-testsuite (311)
      - check-success=ci-testsuite (312)
      - check-success=ci-testsuite (313)
      - check-success=ci-docs
      - check-success=ci-diff
      - check-success=ci-security

pull_request_rules:
  - name: renovate
    actions:
      merge:
        method: rebase
    conditions:
      - author=renovate[bot]
      - label!=no-mergify
      - "#changes-requested-reviews-by=0"
      - check-success=ci-smoketests
      - check-success=ci-typing
      - check-success=ci-testsuite (311)
      - check-success=ci-testsuite (312)
      - check-success=ci-testsuite (313)
      - check-success=ci-docs
      - check-success=ci-diff
      - check-success=ci-security
  - name: default
    actions:
      merge:
        method: rebase
    conditions:
      - label!=no-mergify
      - '#approved-reviews-by>=1'
      - check-success=ci-smoketests
      - check-success=ci-typing
      - check-success=ci-testsuite (311)
      - check-success=ci-testsuite (312)
      - check-success=ci-testsuite (313)
      - check-success=ci-docs
      - check-success=ci-diff
      - check-success=ci-security
