pull_request_rules:
  - name: renovate
    actions:
      merge:
        method: rebase
    conditions:
      - author=renovate[bot]
      - label!=no-mergify
      - "#changes-requested-reviews-by=0"
      - check-success=fedora/check
  - name: default
    actions:
      merge:
        method: rebase
    conditions:
      - label!=no-mergify
      - '#approved-reviews-by>=1'
      - check-success=fedora/check
