rules:
  default:
    protection:
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts:
        - continuous-integration/travis-ci
        - codecov/patch
        - codecov/project
    merge_strategy:
      method: rebase
      rebase_fallback: none
