pull_request_rules:
- actions:
    merge:
      method: rebase
      rebase_fallback: null
      strict: true
  conditions:
  - label!=no-mergify
  - '#approved-reviews-by>=1'
  - check-success=fedora/check
  name: default

