pull_request_rules:
- actions:
    merge:
      method: rebase
      rebase_fallback: null
      strict: true
  conditions:
  - label!=no-mergify
  - '#approved-reviews-by>=1'
  - check-success=continuous-integration/travis-ci/pr
  - check-success=codecov/patch
  - check-success=codecov/project
  name: default

