version: 2

# Formats to generate beside HTML
formats:
  - epub
  - pdf

# Build configuration
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
