version: 2

# Formats to generate beside HTML
formats:
  - epub
  - pdf

# Build configuration
build:
  os: ubuntu-lts-latest
  tools:
    python: "latest"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry
    post_install:
      # VIRTUAL_ENV needs to be set manually for now.
      # See https://github.com/readthedocs/readthedocs.org/pull/11152/
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
