version: 2

# Formats to generate beside HTML
formats:
  - epub
  - pdf

# Python configuration
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
