version: 2

# Formats to generate beside HTML
formats:
  - epub
  - pdf

# Python configuration
python:
  version: "3.10"
  install:
    - requirements: requirements.txt
    - requirements: test_requirements.txt

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
