version: "2.0"

services:
  image-builder:
    image: anitya-base
    build:
      context: .
      dockerfile: Containerfile.dev
      args:
        FEDORA_VERSION: 34

  anitya-web:
    image: anitya-base
    container_name: "anitya-web"
    network_mode: host
    volumes:
      - ./:/app
    privileged: true
    tty: true
    restart: unless-stopped
    depends_on:
      image-builder:
        condition: service_started

  anitya-librariesio-consumer:
    image: anitya-base
    container_name: "anitya-librariesio-consumer"
    network_mode: host
    volumes:
      - ./:/app
    privileged: true
    tty: true
    restart: unless-stopped
    depends_on:
      image-builder:
        condition: service_started

  rabbitmq:
    image: rabbitmq:3.8.16-management-alpine
    container_name: "rabbitmq"
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 3s
      timeout: 3s
      retries: 30
    environment:
      - RABBITMQ_DEFAULT_USER=anitya
      - RABBITMQ_DEFAULT_PASS=anitya

  postgres:
    image: postgres:9.6.22-buster
    container_name: "postgres"
    network_mode: host
    volumes:
      - .container/data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 3s
      retries: 30
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=anypasswordworkslocally
      - POSTGRES_DB=anitya

