############################################
##  Containerfile of anitya libraries.io  ##
############################################

ARG FEDORA_VERSION
FROM fedora:${FEDORA_VERSION}

WORKDIR /app

# Package installation steps are separated so they
# can be cached individually on Dockerfile changes

RUN dnf upgrade --refresh -y
