version: "2.0"

services:
  anitya-web:
    build:
      context: .
      dockerfile: Containerfile.web.dev
      args:
        FEDORA_VERSION: 34
    container_name: "anitya-web"
    network_mode: host
    volumes:
      - ./:/app
    privileged: true
    tty: true
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

          #  anitya-librariesio-consumer:
          #    build:
          #      context: .
          #      dockerfile: Containerfile.lc.dev
          #      args:
          #        FEDORA_VERSION: 32
          #    container_name: "anitya-librariesio-consumer"
          #    network_mode: host
          #    volumes:
          #      - ./:/app
          #    privileged: true
          #    tty: true
          #    restart: unless-stopped
          #
          #  anitya-check-service:
          #    build:
          #      context: .
          #      dockerfile: Containerfile.cs.dev
          #      args:
          #        FEDORA_VERSION: 32
          #    container_name: "anitya-check-service"
          #    network_mode: host
          #    volumes:
          #      - ./:/app
          #    privileged: true
          #    tty: true
          #    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.8.16-management-alpine
    container_name: "rabbitmq"
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 3s
      timeout: 3s
      retries: 30
    environment:
      - RABBITMQ_DEFAULT_USER=anitya
      - RABBITMQ_DEFAULT_PASS=anitya

  postgres:
    image: postgres:9.6.22-buster
    container_name: "postgres"
    network_mode: host
    volumes:
      - .container/data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 3s
      retries: 30
    environment:
      - POSTGRES_PASSWORD=anitya
      - POSTGRES_USER=anitya
      - POSTGRES_DB=anitya

