version: "2.0"

services:
  anitya-web:
    image: anitya-base
    build:
      context: .
      dockerfile: Containerfile.dev
      args:
        FEDORA_VERSION: 36
    container_name: "anitya-web"
    ports:
      - "5000:5000"
    volumes:
      - ./:/app:z
    privileged: true
    restart: unless-stopped
    environment:
      - FLASK_APP=anitya.wsgi
      - START_COMMAND=flask run
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started

  anitya-librariesio-consumer:
    image: anitya-base
    build:
      context: .
      dockerfile: Containerfile.dev
      args:
        FEDORA_VERSION: 36
    container_name: "anitya-librariesio-consumer"
    volumes:
      - ./:/app:z
    privileged: true
    restart: unless-stopped
    environment:
      - START_COMMAND=librariesio_consumer.py
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started

  rabbitmq:
    image: docker.io/library/rabbitmq:3.8.16-management-alpine
    container_name: "rabbitmq"
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 3s
      timeout: 3s
      retries: 30
    environment:
      - RABBITMQ_DEFAULT_USER=anitya
      - RABBITMQ_DEFAULT_PASS=anitya

  postgres:
    image: docker.io/library/postgres:13.4
    container_name: "postgres"
    user: postgres
    ports:
      - "5432:5432"
    volumes:
      - .container/dump:/dump
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 3s
      retries: 30
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=anypasswordworkslocally
      - POSTGRES_DB=anitya

