# Containerfile of anitya web

ARG FEDORA_VERSION
FROM fedora:${FEDORA_VERSION}

WORKDIR /app

# Package installation steps are separated so they
# can be cached individually on Dockerfile changes

RUN dnf upgrade --refresh -y

# Python3 and packages
RUN dnf install -y python3-psycopg2

# Fedora Messaging
RUN dnf install -y fedora-messaging

COPY . .

RUN mkdir -p /etc/anitya
RUN cp /app/ansible/roles/anitya-dev/files/anitya.toml /etc/anitya

# Pip installations
RUN pip3 install -r /app/test_requirements.txt
RUN pip3 install -r /app/requirements.txt
RUN pip3 install -e /app

EXPOSE 5000
