version: "2.0"

services:
  image-builder:
    image: anitya-base
    build:
      context: .
      dockerfile: Containerfile.dev
      args:
        FEDORA_VERSION: 34

  anitya-web:
    image: anitya-base
    container_name: "anitya-web"
    network_mode: host
    volumes:
      - ./:/app
    privileged: true
    restart: unless-stopped
    depends_on:
      image-builder:
        condition: service_started
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started

  anitya-librariesio-consumer:
    image: anitya-base
    container_name: "anitya-librariesio-consumer"
    network_mode: host
    volumes:
      - ./:/app
    privileged: true
    restart: unless-stopped
    depends_on:
      image-builder:
        condition: service_started
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started

  rabbitmq:
    image: docker.io/library/rabbitmq:3.8.16-management-alpine
    container_name: "rabbitmq"
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 3s
      timeout: 3s
      retries: 30
    environment:
      - RABBITMQ_DEFAULT_USER=anitya
      - RABBITMQ_DEFAULT_PASS=anitya

  postgres:
    image: docker.io/library/postgres:13.4
    container_name: "postgres"
    network_mode: host
    volumes:
      - .container/postgresql:/var/lib/postgresql
      - .container/dump:/dump
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 3s
      retries: 30
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=anypasswordworkslocally
      - POSTGRES_DB=anitya

