# Containerfile of anitya web

ARG FEDORA_VERSION
FROM fedora:${FEDORA_VERSION}

WORKDIR /app

# Package installation steps are separated so they
# can be cached individually on Dockerfile changes

RUN dnf upgrade --refresh -y

# Project dependencies
RUN dnf install -y gcc graphviz make libffi-devel openssl-devel

# Python3 and packages
RUN dnf install -y python3 python3-pip python3-devel python36 python37 python3-black \
    python3-tox python3-psycopg2 python3-sphinxcontrib-httpdomain python3-sqlalchemy_schemadisplay \
    python3-alembic python3-arrow python3-dateutil python3-defusedxml python3-flask-login python3-flask-restful \
    python3-flask-wtf python3-jinja2 python3-ordered-set python3-pytoml python3-semver python3-social-auth-app-flask \
    python3-social-auth-app-flask-sqlalchemy python3-sqlalchemy python3-sseclient python3-straight-plugin python3-wtforms

# Fedora Messaging
RUN dnf install -y fedora-messaging

COPY . .

# Install local packages in editable mode
RUN pip install -e /app
RUN pip install -e /app/anitya_schema

RUN python setup.py develop

EXPOSE 5000
