- hosts: all
  tasks:
    - name: Print job dependencies
      debug:
        var: job_dependencies

    - name: Install dependencies
      dnf:
        name:
          "{{job_dependencies}}"
      become: True
      when: (job_dependencies is defined) and (job_dependencies|length > 0)

    - name: Print dependencies
      debug:
        var: dependencies

    - name: Install dependencies
      dnf:
        name:
          "{{dependencies}}"
      become: True
      when: (dependencies is defined) and (dependencies|length > 0)

    - name: Run test
      command: tox -e {{tox_env}}
      args:
        chdir: "{{ansible_user_dir}}/{{zuul.project.src_dir}}"
